### ISSUE TITLE
the sadness_score is not in data row

### ISSUE THREAD

**Issue by kai-niu** [kai-niu/watson-transformer#6]
when using NLU result parser, the sadness_score key is not presented in the row sometimes.

**Comment by kai-niu** [comment]
Traceback (most recent call last):
  File "/opt/ibm/spark/python/lib/pyspark.zip/pyspark/worker.py", line 253, in main
    process()
  File "/opt/ibm/spark/python/lib/pyspark.zip/pyspark/worker.py", line 248, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/opt/ibm/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 331, in dump_stream
    self.serializer.dump_stream(self._batched(iterator), stream)
  File "/opt/ibm/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 140, in dump_stream
    for obj in iterator:
  File "/opt/ibm/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 320, in _batched
    for item in iterator:
  File "<string>", line 1, in <lambda>
  File "/opt/ibm/spark/python/lib/pyspark.zip/pyspark/worker.py", line 74, in <lambda>
    return lambda *a: toInternal(f(*a))
  File "/opt/ibm/spark/python/lib/pyspark.zip/pyspark/sql/types.py", line 612, in toInternal
    return tuple(obj[n] for n in self.names)
  File "/opt/ibm/spark/python/lib/pyspark.zip/pyspark/sql/types.py", line 612, in <genexpr>
    return tuple(obj[n] for n in self.names)
  File "/opt/ibm/spark/python/lib/pyspark.zip/pyspark/sql/types.py", line 1548, in __getitem__
    raise ValueError(item)
ValueError: sadness_score
